### ISSUE TITLE
Tree-like structure for suppressed rules.

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/jtcop#129]
Currently `TestCase` and `TestClass` have their own independent suppressed lists. We have to concat them.
In other words all methods of the class has to have all suppressed rules of the parent class. The same logic works with Project -> Class relationship.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#135](https://github.com/volodya-lombrozo/jtcop/issues/135), [#136](https://github.com/volodya-lombrozo/jtcop/issues/136), [#137](https://github.com/volodya-lombrozo/jtcop/issues/137) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#135](https://github.com/volodya-lombrozo/jtcop/issues/135), [#136](https://github.com/volodya-lombrozo/jtcop/issues/136) are still not solved; solved: [#137](https://github.com/volodya-lombrozo/jtcop/issues/137).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#135](https://github.com/volodya-lombrozo/jtcop/issues/135) is still not solved; solved: [#136](https://github.com/volodya-lombrozo/jtcop/issues/136), [#137](https://github.com/volodya-lombrozo/jtcop/issues/137).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 3 puzzles are solved here: [#135](https://github.com/volodya-lombrozo/jtcop/issues/135), [#136](https://github.com/volodya-lombrozo/jtcop/issues/136), [#137](https://github.com/volodya-lombrozo/jtcop/issues/137).
