### ISSUE TITLE
Test class may only have methods annotated with @Test

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/jtcop#194]
A test class may only have methods annotated with @Test (in the case of Java). Maybe we have to add the check for it.

**Comment by volodya-lombrozo** [comment]
Maybe it makes sense to introduce "experimental features"

**Comment by 0pdd** [comment]
@volodya-lombrozo 4 puzzles [#230](https://github.com/volodya-lombrozo/jtcop/issues/230), [#231](https://github.com/volodya-lombrozo/jtcop/issues/231), [#232](https://github.com/volodya-lombrozo/jtcop/issues/232), [#233](https://github.com/volodya-lombrozo/jtcop/issues/233) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#230](https://github.com/volodya-lombrozo/jtcop/issues/230), [#231](https://github.com/volodya-lombrozo/jtcop/issues/231), [#232](https://github.com/volodya-lombrozo/jtcop/issues/232) are still not solved; solved: [#233](https://github.com/volodya-lombrozo/jtcop/issues/233).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#230](https://github.com/volodya-lombrozo/jtcop/issues/230), [#231](https://github.com/volodya-lombrozo/jtcop/issues/231) are still not solved; solved: [#232](https://github.com/volodya-lombrozo/jtcop/issues/232), [#233](https://github.com/volodya-lombrozo/jtcop/issues/233).

**Comment by 0pdd** [comment]
@volodya-lombrozo 3 puzzles [#230](https://github.com/volodya-lombrozo/jtcop/issues/230), [#231](https://github.com/volodya-lombrozo/jtcop/issues/231), [#245](https://github.com/volodya-lombrozo/jtcop/issues/245) are still not solved; solved: [#232](https://github.com/volodya-lombrozo/jtcop/issues/232), [#233](https://github.com/volodya-lombrozo/jtcop/issues/233).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#231](https://github.com/volodya-lombrozo/jtcop/issues/231), [#245](https://github.com/volodya-lombrozo/jtcop/issues/245) are still not solved; solved: [#230](https://github.com/volodya-lombrozo/jtcop/issues/230), [#232](https://github.com/volodya-lombrozo/jtcop/issues/232), [#233](https://github.com/volodya-lombrozo/jtcop/issues/233).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#231](https://github.com/volodya-lombrozo/jtcop/issues/231), [#266](https://github.com/volodya-lombrozo/jtcop/issues/266) are still not solved; solved: [#230](https://github.com/volodya-lombrozo/jtcop/issues/230), [#232](https://github.com/volodya-lombrozo/jtcop/issues/232), [#233](https://github.com/volodya-lombrozo/jtcop/issues/233), [#245](https://github.com/volodya-lombrozo/jtcop/issues/245).
