### ISSUE TITLE
Only `Test` and `ITCase` suffixes

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/jtcop#195]
a package with tests may only have classes with `Test` or `ITCase` suffixes that map one-to-one to live classes and nothing else.

**Comment by volodya-lombrozo** [comment]
Maybe we need to create an issue for that check.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#215](https://github.com/volodya-lombrozo/jtcop/issues/215), [#216](https://github.com/volodya-lombrozo/jtcop/issues/216) are still not solved.

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#215](https://github.com/volodya-lombrozo/jtcop/issues/215), [#218](https://github.com/volodya-lombrozo/jtcop/issues/218) are still not solved; solved: [#216](https://github.com/volodya-lombrozo/jtcop/issues/216).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#218](https://github.com/volodya-lombrozo/jtcop/issues/218) is still not solved; solved: [#215](https://github.com/volodya-lombrozo/jtcop/issues/215), [#216](https://github.com/volodya-lombrozo/jtcop/issues/216).

**Comment by 0pdd** [comment]
@volodya-lombrozo all 3 puzzles are solved here: [#215](https://github.com/volodya-lombrozo/jtcop/issues/215), [#216](https://github.com/volodya-lombrozo/jtcop/issues/216), [#218](https://github.com/volodya-lombrozo/jtcop/issues/218).
