### ISSUE TITLE
Dumb tests rule

### ISSUE THREAD

**Issue by l3r8yJ** [volodya-lombrozo/jtcop#242]
@volodya-lombrozo hi, today I found this test in the project I am working in, I have an idea to have jtcop detect tests that are not acceptable for jtcop.
![image](https://github.com/volodya-lombrozo/jtcop/assets/46355873/b68f74f1-fac2-4692-b460-89dc4ff606b8)

We can discuss a solution here, what do you think?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ as I see it, this name follows the next pattern rule:
```
void <given>_<condition>*_<result>(){
}
```
And it might be "ok" for some projects. What exactly do you want to change in this name? Do you want to forbid using underscores? Or in opposite, do you want to allow such a pattern?

**Comment by l3r8yJ** [comment]
@volodya-lombrozo I'm not talking about the name with underscores, but about the bad `assertTrue(true)` statement, which is written to falsely increase the coverage of the code

**Comment by volodya-lombrozo** [comment]
@l3r8yJ I see your point here. Thanks for the explanation :) Actually, it is awesome idea. 
We have many unit testing anti-patterns:
- https://stackoverflow.com/questions/333682/unit-testing-anti-patterns-catalogue
- https://www.yegor256.com/2018/12/11/unit-testing-anti-patterns.html

What you are talking about is a "Line hitter":
> At first glance, the tests cover everything and code coverage tools confirm it with 100%, but in reality the tests merely hit the code, without doing any output analysis.

And you are right, we can help to catch such "line hitters". Maybe you have more examples?

**Comment by l3r8yJ** [comment]
@volodya-lombrozo I'll try to find more examples from the real projects

**Comment by h1alexbel** [comment]
@volodya-lombrozo @l3r8yJ it will be great if such a rule appears

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#254](https://github.com/volodya-lombrozo/jtcop/issues/254) is still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#254](https://github.com/volodya-lombrozo/jtcop/issues/254) is solved here.
