### ISSUE TITLE
Test classes should not have parent classes

### ISSUE THREAD

**Issue by yegor256** [volodya-lombrozo/jtcop#314]
I suggest to introduce a check, that will prohibit JUnit test classes to have a parent class. Here is why:

  * https://www.petrikainulainen.net/programming/unit-testing/3-reasons-why-we-should-not-use-inheritance-in-our-tests/
  * https://ncorti.com/blog/junit-rules
  * https://coderanch.com/t/698727/engineering/bad-practice-test-classes-extend
  * https://www.testingdocs.com/disadvantages-of-using-inherited-tests-in-junit/

**Comment by yegor256** [comment]
@volodya-lombrozo please, consider this feature

**Comment by volodya-lombrozo** [comment]
@yegor256 It's a good suggestion. Thank you!

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#318](https://github.com/volodya-lombrozo/jtcop/issues/318) is still not solved.

**Comment by volodya-lombrozo** [comment]
@yegor256 The feature should be added in the '1.0.2' version

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#318](https://github.com/volodya-lombrozo/jtcop/issues/318) is solved here.
