### ISSUE TITLE
RuleTestCaseContainsMockeryTest.java:37-39: Create...

### ISSUE THREAD

**Issue by 0pdd** [volodya-lombrozo/jtcop#398]
The puzzle `393-ce5b79b8` from #393 has to be resolved: 

https://github.com/volodya-lombrozo/jtcop/blob/4a1b030ce58d445df115907ae8d3e81cfe40178f/src/test/java/com/github/lombrozo/testnames/rules/RuleTestCaseContainsMockeryTest.java#L37-L39

The puzzle was created by h1alexbel on 11-Jul-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
@volodya-lombrozo can I take this one?

**Comment by volodya-lombrozo** [comment]
@h1alexbel Sure, please go ahead!
