### ISSUE TITLE
deep profile for running slow tests

### ISSUE THREAD

**Issue by h1alexbel** [volodya-lombrozo/jtcop#429]
> @h1alexbel It's a good thing actually! However I suggest to keep in this PR only the changes relevant to the #101 issue. We can add this `deep` profile in a separate PR. What do you think?

_Originally posted by @volodya-lombrozo in https://github.com/volodya-lombrozo/jtcop/pull/428#discussion_r1756828236_

**Comment by volodya-lombrozo** [comment]
@h1alexbel Sure. Please, go ahead!
