### ISSUE TITLE
Rename Maven goal to 'check-test-names`

### ISSUE THREAD

**Issue by yegor256** [volodya-lombrozo/jtcop#61]
The name `check-tests-names` is grammatically incorrect: https://english.stackexchange.com/questions/227378/usage-of-double-plural. The correct phrase would be `test names` instead of `tests names`.

**Comment by volodya-lombrozo** [comment]
@yegor256 Is it still relevant?

**Comment by yegor256** [comment]
@volodya-lombrozo now it's all good
