### ISSUE TITLE
Rename entire plugin

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/jtcop#62]
For now, in order to use plugin directly to the project we have to write the next command to the command line:
```
mvn com.github.volodya-lombrozo:test-naming-conventions:check
```
Which is quite long name, as to me, I would like to use something like:
```
mvn testcop:check
```
or 
```
mvn test-cop:check
```

In order to do so we have to rename entire plugin to the:
```
testcop-maven-plugin
```
___
_I'm not sure about the final name of the plugin._

**Comment by volodya-lombrozo** [comment]
@yegor256, Could we borrow your idea about the plugin naming strategy? :) 
I want to use something like `testcop`, or `test-cop`. What do you think?

**Comment by yegor256** [comment]
@volodya-lombrozo it's not my idea, I got it from here: https://rubocop.org/ :)

**Comment by yegor256** [comment]
@volodya-lombrozo maybe you can extend the functionality of your plugin and make it check not only names of test methods, but also the layout of tests in the `src/test` directory, according to the principles I explained here: https://www.yegor256.com/2023/01/19/layout-of-tests.html In this case, maybe you can rename the plugin to `jucop` (jUnit Cop). It will check all possible aspects of test layout in Java projects: file naming, class naming, method naming, location of files, names of directories, etc.

**Comment by volodya-lombrozo** [comment]
Hey @yegor256, Thanks a lot for your suggestion! I really appreciate it and I'm definitely going to implement it. The only thing is, I'm not sure about the plugin name. `jucop` seems like a good choice for now (maybe even the best), but I don't want to limit the plugin to just `JUnit` testing framework. We might be able to help developers using other frameworks like [TestNG](https://testng.org/doc/) too.

**Comment by volodya-lombrozo** [comment]
Okey, if I won't imagine something else, we will get `jucop`.

**Comment by yegor256** [comment]
@volodya-lombrozo yes, indeed, other frameworks must also be taken into account. Maybe `jtcop` (Java Test Cop). Anyway, I'm just throwing ideas :) Pick the name _you_ like.
