### ISSUE TITLE
Check class names

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/jtcop#66]
Here is the [article](https://www.yegor256.com/2023/01/19/layout-of-tests.html) about several suggestions related to good practices that could be applied for Java tests. 

The one of the suggestions is that each test class has to be related to the real class in the working tree. In other words, each test case from `src\test` folder has to be related to a real class in `src\main` folder: 
```
JavaTestCode -> JavaTestCodeTest
JavaParserCase -> JavaParserCaseTest
PresentSimpleRule -> PresentSimpleRuleTest
```
etc

> My point is that the name of a test class is not just a name. It’s an instruction for a wondering programmer: “Go look into the source file, the name of which you can derive from my name, removing the Test suffix.” If I try to follow this instruction and it leads me nowhere, I get very frustrated, especially if the project is not mine. I can’t get the required information from anywhere else. The name of the test class is my last hope.

**Comment by yegor256** [comment]
@volodya-lombrozo still not implemented? Would be great to have this feature.

**Comment by volodya-lombrozo** [comment]
@yegor256 Actually it's already implemented. For example, that [PR](https://github.com/objectionary/eo/actions/runs/4845869330/jobs/8645635652?pr=1993) can't be merged because:
```java
Test TyposTest.java doesn't have corresponding production class.
[166](https://github.com/objectionary/eo/actions/runs/4845869330/jobs/8645635652?pr=1993#step:5:167)
	You can either rename or move the test class /home/runner/work/eo/eo/eo-parser/src/test/java/org/eolang/parser/TyposTest.java:
[167](https://github.com/objectionary/eo/actions/runs/4845869330/jobs/8645635652?pr=1993#step:5:168)
	More about that rule you can read here https://www.yegor256.com/2023/01/19/layout-of-tests.html#test-classes
```
