### ISSUE TITLE
Specify information about IT

### ISSUE THREAD

**Issue by l3r8yJ** [volodya-lombrozo/jtcop#70]
@volodya-lombrozo in the integration test we have a groovy script that checks the `build.log` file, could you clarify one thing? What tool do we use to create this file or something like that, i.e. what makes this file appear?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ It is [maven-invoker-plugin](https://maven.apache.org/plugins/maven-invoker-plugin/).

```xml
      <plugin>
        <artifactId>maven-invoker-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <cloneProjectsTo>${project.build.directory}/it</cloneProjectsTo>
          <settingsFile>src/it/settings.xml</settingsFile>
          <localRepositoryPath>${project.build.directory}/local-repo
          </localRepositoryPath>
          <postBuildHookScript>verify</postBuildHookScript>
          <streamLogsOnFailures>true</streamLogsOnFailures>
        </configuration>
        <executions>
          <execution>
            <id>integration-test</id>
            <goals>
              <goal>install</goal>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
It actually has quite a good [example](https://maven.apache.org/plugins/maven-invoker-plugin/usage.html):
> The output of the IT builds is written to a log file named build.log (e.g. target/it/first-it/build.log) and allows diagnostics in case an integration test fails.

**Comment by l3r8yJ** [comment]
@volodya-lombrozo thanks, I already use Invoker in some projects, but have never seen the logging file
