### ISSUE TITLE
Suppress checks for some tests

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/jtcop#78]
It's quite useful to suppress some checks for some tests

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#114](https://github.com/volodya-lombrozo/jtcop/issues/114), [#115](https://github.com/volodya-lombrozo/jtcop/issues/115) are still not solved; solved: [#110](https://github.com/volodya-lombrozo/jtcop/issues/110).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#115](https://github.com/volodya-lombrozo/jtcop/issues/115), [#117](https://github.com/volodya-lombrozo/jtcop/issues/117) are still not solved; solved: [#110](https://github.com/volodya-lombrozo/jtcop/issues/110), [#114](https://github.com/volodya-lombrozo/jtcop/issues/114).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#117](https://github.com/volodya-lombrozo/jtcop/issues/117) is still not solved; solved: [#110](https://github.com/volodya-lombrozo/jtcop/issues/110), [#114](https://github.com/volodya-lombrozo/jtcop/issues/114), [#115](https://github.com/volodya-lombrozo/jtcop/issues/115).

**Comment by 0pdd** [comment]
@volodya-lombrozo 2 puzzles [#125](https://github.com/volodya-lombrozo/jtcop/issues/125), [#126](https://github.com/volodya-lombrozo/jtcop/issues/126) are still not solved; solved: [#110](https://github.com/volodya-lombrozo/jtcop/issues/110), [#114](https://github.com/volodya-lombrozo/jtcop/issues/114), [#115](https://github.com/volodya-lombrozo/jtcop/issues/115), [#117](https://github.com/volodya-lombrozo/jtcop/issues/117).

**Comment by 0pdd** [comment]
@volodya-lombrozo the puzzle [#125](https://github.com/volodya-lombrozo/jtcop/issues/125) is still not solved; solved: [#110](https://github.com/volodya-lombrozo/jtcop/issues/110), [#114](https://github.com/volodya-lombrozo/jtcop/issues/114), [#115](https://github.com/volodya-lombrozo/jtcop/issues/115), [#117](https://github.com/volodya-lombrozo/jtcop/issues/117), [#126](https://github.com/volodya-lombrozo/jtcop/issues/126).

**Comment by volodya-lombrozo** [comment]
I close that issue since all the related puzzles were solved.
